### ISSUE TITLE
issue with the question

### ISSUE THREAD

**Issue by MokiMeow** [sanidhyy/quill#3]
![image](https://github.com/sanidhyy/quill/assets/122464960/da444ebc-eb7e-4c0e-ae89-1f665f5fca41)

hey, tired to implement ur prj while doing i kept on getting this problem on too many pages wheni only had 1 , u have any idea why, in ur deployed url its happening

**Comment by sanidhyy** [comment]
My OpenAI key has expired, you can deploy it yourself with your own key.
